pub mod system_state;
pub mod kill_switch;
pub mod config;
pub mod metrics;
pub mod journal;
pub mod heartbeat;
pub mod command_channel;
pub mod config_watcher;
pub mod api;
pub mod ws;
pub mod threading;
pub mod validator;
pub mod idempotency;
pub mod position_manager;
pub mod symbol_registry;

pub use kill_switch::KillSwitch;
pub use metrics::GlobalMetrics;
pub use system_state::SystemState;
pub use config::EngineConfig;
pub use journal::JournalWriter;
pub use journal::JournalEntry;
pub use heartbeat::ThreadHeartbeatMonitor;
pub use command_channel::{CommandChannel, CommandActor, ControlCommand, ControlResponse};
pub use config_watcher::ConfigWatcher;
pub use api::{create_router, ApiState};
pub use ws::{create_ws_router, WsState};
pub use threading::{pin_to_core, set_thread_priority, spawn_pinned, ThreadPriority};
pub use validator::RequestValidator;
pub use idempotency::IdempotencyStore;
pub use position_manager::PositionManager;
pub use symbol_registry::{SymbolRegistry, SymbolId, SymbolIdArray, MAX_SYMBOLS};
